const SET_CAROUSEL = 'SET_CAROUSEL';
const SET_LIST_FILM = 'SET_LIST_FILM';
const SET_FILM_DANG_CHIEU = 'SET_FILM_DANG_CHIEU';
const SET_FILM_SAP_CHIEU = 'SET_FILM_SAP_CHIEU';
export { SET_CAROUSEL, SET_LIST_FILM, SET_FILM_DANG_CHIEU, SET_FILM_SAP_CHIEU }



// CINEMA

const SET_LIST_CINEMA = 'SET_LIST_CINEMA';
const SET_SCHEDULE_FILM = 'SET_SCHEDULE_FILM'
export { SET_LIST_CINEMA, SET_SCHEDULE_FILM }



//USER

const SET_LOG_IN = 'SET_LOG_IN';
const SET_USER_INFO_FULL = 'SET_USER_INFO_FULL';
const SET_ACCOUNT_FULL = 'SET_ACCOUNT_FULL';
export { SET_LOG_IN, SET_USER_INFO_FULL, SET_ACCOUNT_FULL }


// BOOKING

const SET_FILM_BOOKING = 'SET_FILM_BOOKING';
const SET_DAT_VE = 'SET_DAT_VE';
export { SET_FILM_BOOKING, SET_DAT_VE }